version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine

    steps:

      - checkout

      - restore_cache:
          key: circleci-spring5-recipe-app-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-spring5-recipe-app-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/spring5-recipe-app-0.0.1-SNAPSHOT.jar